### ISSUE TITLE
Feature Suggestion: Show addon only to admins

### ISSUE THREAD

**Issue by vierkantemeter** [sergant210/controlErrorLog#1]
Hi there,

First of all; thanks for this great add-on! Works really well.

I have a small feature suggestion; option to show the add-on only to users who have admin privileges. Now, my customers (content editors) also see this, and I'm sure it will freak them out  :stuck_out_tongue: (although there are no critical errors in the log).

EDIT:
For now, I hard-coded the following in the controlErrorLog plug-in. But it would be nice to have this managed with an ACL or system setting.

```
if ($modx->user->isMember('Administrator')) {
// controlErrorLog code
}
```

**Comment by sergant210** [comment]
Hi. May be you're right.
