### ISSUE TITLE
Manager blank screen (PHP Fatal error Allowed memory size of xx bytes exhausted)

### ISSUE THREAD

**Issue by vierkantemeter** [sergant210/controlErrorLog#14]
My error log grown to 60MB which causes the manager to show the white screen of death (500). The Apache error log says:

`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 68499221 bytes) in /home/xxx/domains/xxx.nl/public_html/core/components/controlerrorlog/processors/mgr/errorlog/get.class.php on line 40, referer: http://www.xxx.nl/manager/?a=workspaces`

When I disable controlErrorlog, everything is working back normal. I guess this add-on may need some modification so it will not break up the manager when the error log become so large. Raising the memory_limit doesn't sound like a solution.

MODX 2.5.0
controlerrorlog 1.1.2

**Comment by soulcreate** [comment]
I too have this error, when I login to /manager/ as root user:
У меня такая же ошибка, когда я захожу в админку под рутом:
```
[error] 5628#0: *31508500 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 92918200 bytes) in www/core/components/controlerrorlog/processors/mgr/errorlog/get.class.php on line 40" while reading response header from upstream, request: "GET /manager/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7-www.sock:"
```
