### ISSUE TITLE
Problem with merging menu items

### ISSUE THREAD

**Issue by GulomovCreative** [sergant210/controlErrorLog#19]
![screenshot-resto-food ru-2018 11 29-14-29-44](https://user-images.githubusercontent.com/20814058/49206127-ab305f80-f3e3-11e8-9615-d4318b81a246.png)

Мне кажется, что добавив `margin-left: 15px` ссылке было бы логичнее ну или Илье добавить внутренние отступы

**Comment by sergant210** [comment]
Либо, либо. Только наверно margin-left.

П.С. Интересно, а зачем нужна кнопка обновления в меню-баре? Она используется не чаще, чем раз в полгода.

**Comment by GulomovCreative** [comment]
Да, опечатался, margin-left

Как зачем? Скоро же MODX3 (шутка)

Как хотите, я просто увидел и написал)

**Comment by GulomovCreative** [comment]
Илья в simpleUpdater исправил у себя, закрываю
