### ISSUE TITLE
Feature Suggestion: Error message in MODX manager template style

### ISSUE THREAD

**Issue by vierkantemeter** [sergant210/controlErrorLog#2]
Maybe you can style the error message so it will blend more in the MODX template. Maybe something like this when there are errors:

![voila_capture 2015-07-30_04-40-51_pm](https://cloud.githubusercontent.com/assets/487567/8985899/c3d9c848-36d9-11e5-8aa7-b0e53cf12767.jpg)

I've used a Font Awesome icon (fa-exclamation-triangle)

**Comment by sergant210** [comment]
It looks nice with other icons.

**Comment by vierkantemeter** [comment]
Awesome! :ok_hand:
