### ISSUE TITLE
После обновления до 1.4.0 ошибка Processor get.php does not exist; Array

### ISSUE THREAD

**Issue by DetaliDigital** [sergant210/controlErrorLog#23]
После обновления пакета controlErrorLog в логе печатается ошибка:

![изображение](https://user-images.githubusercontent.com/20732384/92631641-4d2fec00-f2da-11ea-8783-a48387370e1c.png)

Кэш чистил, пакет устанавливал повторно. Хотелось бы убрать данную ошибку.

**Comment by sergant210** [comment]
Ctrl + F5.

**Comment by DetaliDigital** [comment]
Да, прошу прощения за беспокойство. Это действительно был кэш.
