### ISSUE TITLE
Caching issues

### ISSUE THREAD

**Issue by Jako** [sergant210/controlErrorLog#24]
Maybe there occur caching issues with the new frontend mode of 1.4.0-beta.

I have currently faced FormIt &store=1 / FormItRetriever issues on a customer installation. The MODX error log was full of entries with 'Error caching script elements/modplugin/…'‚ 'Could not cache resource', 'Error caching script elements/modsnippet/…', 'Error caching lexicon topic‘ etc. After switching back to controlErrorLog 1.3.1 these errors don't occur anymore.

**Comment by sergant210** [comment]
It's strange. ControlErrorLog doesn't lock any cache file. Do these issues appear again if you update controlErrorLog to version 1.4.0? Did you try to disable the **control_frontend** setting or **format_output** setting?

**Comment by Jako** [comment]
I can’t install it there again.

**Comment by sergant210** [comment]
For the experiment, I disabled the ControlErrorLog plugin, cleared the cache, refreshed the page. I've done it several times. These caching issues reappeared. So it does not depend on ControlErrorLog.

**Comment by Jako** [comment]
Maybe the cache was broken and was reset after uninstalling and installing the package again.
