### ISSUE TITLE
Stray smarty cache files

### ISSUE THREAD

**Issue by Jako** [sergant210/controlErrorLog#31]
In my dev installation, two smarty cache files keep getting created with controlErrorLog:
`connectors/templates_c/d4950c01bccb92e00cdc1a79bf982dcb935bad5f_0.file.error_table.tpl.php`
`manager/templates_c/134737f2061d5f48150095cc746cd70ab4600292_0.file.error_table.tpl.php`

Normally the smarty cache is located in `core/cache/mgr/smarty`.

ControlErrorLog 1.4.5

**Comment by sergant210** [comment]
Fixed in v.1.4.6.
