### ISSUE TITLE
Plugin loses lexicon strings with some CMPs

### ISSUE THREAD

**Issue by BobRay** [sergant210/controlErrorLog#6]
On my system, with some CMP extras all the lexicon strings are missing when the window comes up. It happens with Batcher, PackMan, and SiteCheck, but not Quip or Discuss.

It seems to only happen while the CMP is open. If you go to the dashboard or edit an object in the Manager, or log out and back in, it's back to normal.

I can't figure out why it's happening. I wonder if it might be because you're calling $modx->controller->addLexiconTopic('controlerrorlog:default'); instead of $modx->lexicon->load().

**Comment by sergant210** [comment]
I got the same problem with CMPGenerator. I guess this problem occurs in Extras created from Doodles Extra. I use modExtra for creating my Extras. There is no problem with them. 
I'll try to find out the cause of this problem.

**Comment by BobRay** [comment]
SiteCheck and Orphans are not from Doodles, but I think they use some code from Batcher -- same author as Doodles. I suspect that any CMP created with MyComponent will cause the same trouble. I wonder if iFrames are the issue.

It's not that big a deal, since I remember which button is which and I think it still shows the errors (though come to think of it, I haven't actually checked).

I have a similar problem with clearing the cache in the Manager. It sometimes comes up blank until I reload the page, though it's somewhat better in 2.4.0.

**Comment by sergant210** [comment]
I do not understand why this is happening. But I found another solution 
```
text: _("cel_refresh") ? _("cel_refresh") : 'Refresh'
```
