### ISSUE TITLE
controllErrorLog not showing up

### ISSUE THREAD

**Issue by terrybarth** [sergant210/controlErrorLog#9]
First, thanks for a great plugin. I use it on all my sites.

I just upgraded an older site from 2.3 to 2.4 and then installed controllErrorLog, but it is not showing up on the menu bar. I am the main admin, sudo user. There are no errors in the log. I've not made any changes to the ACL. I've uninstalled it, manually cleared the cache and reinstalled. It's still not showing up.

Any suggestions?

**Comment by sergant210** [comment]
I have no idea. All my sites work on MODX > 2.4. There is no problem with controllErrorLog. I can say some definite if I see it closer.

**Comment by terrybarth** [comment]
Yeah, it is weird. It works on every other site I have.

I setup a guest manager login for you if you'd like take a look.

Can I send the login credentials to you on this email?


[image: logo]
*Terry Barth Design* *, Website Development*
612 859 2453 | 730 Stinson Blvd NE #103 | terrybarth@terrybarth.com |
www.terrybarthdesign.com
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=264874850853247>

**Comment by sergant210** [comment]
Yes, sure.

**Comment by terrybarth** [comment]
http://74.220.215.106/~passthe3/manager/?

guest

guest2016


[image: logo]
*Terry Barth Design* *, Website Development*
612 859 2453 | 730 Stinson Blvd NE #103 | terrybarth@terrybarth.com |
www.terrybarthdesign.com
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=396008765542959>

**Comment by sergant210** [comment]
Sorry, but I have edited the controlErrorLog plugin and I probably made an error. And now manager can’t be opened. Can you deactivate the plugin&

**Comment by sergant210** [comment]
The easiest way is rename plugin event name in the switch conditions (add “1” to it) in the controlErrorLog cache file (example path <http://joxi.ru/a2XKV6Ycy9y3Vm> )

**Comment by terrybarth** [comment]
Done.


[image: logo]
*Terry Barth Design* *, Website Development*
612 859 2453 | 730 Stinson Blvd NE #103 | terrybarth@terrybarth.com |
www.terrybarthdesign.com
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=428827604332878>

**Comment by sergant210** [comment]
Problem with compressing css. I switched it off and ControlErrorLog is showing now.

**Comment by terrybarth** [comment]
Sergey

I'm not sure what your telling me.

It looks like it's working now. Do I still have to do something?

Do you know what the problem was?


[image: logo]
*Terry Barth Design* *, Website Development*
612 859 2453 | 730 Stinson Blvd NE #103 | terrybarth@terrybarth.com |
www.terrybarthdesign.com
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=896576113833468>

**Comment by sergant210** [comment]
The problem was in compressing css. I set the system setting “compress_css” to false. Now ControlErrorLog is working.

Some advice. Install Ace or CodeMirror for element development.

**Comment by terrybarth** [comment]
Hmmm, interesting. That usually creates other problems, so I almost always
have to switch that off.

Thank you so much for taking a look!

I really appreciate it.


[image: logo]
*Terry Barth Design* *, Website Development*
612 859 2453 | 730 Stinson Blvd NE #103 | terrybarth@terrybarth.com |
www.terrybarthdesign.com
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=537147441831910>

**Comment by terrybarth** [comment]
Will do. I use Ace on all my sites now. This site was started a year and a
half ago, never finished, now back to life.


[image: logo]
*Terry Barth Design* *, Website Development*
612 859 2453 | 730 Stinson Blvd NE #103 | terrybarth@terrybarth.com |
www.terrybarthdesign.com
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=465014812304541>
